# Generated by Django 3.0.4 on 2021-03-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210225_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='emergencyNotification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='emergencyNumber',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
